### ISSUE TITLE
context doesn't work when called through microservices

### ISSUE THREAD

**Issue by rishavchhajer** [skonves/express-http-context#14]
suppose i have 2 micro-service  , **service a** and **service b**
when i call some api of **service b** through **service a** , httpContext.get('key') returns undefined
I have same implementation of **express-http-context** in both the service a and b

P.S  when i am calling individual api through postman , context works wonderfully.

please help

**Comment by anubhav756** [comment]
See https://www.npmjs.com/package/express-http-context#troubleshooting

**Comment by rishavchhajer** [comment]
@anubhav756  thanks.
