### ISSUE TITLE
Use Async Hooks

### ISSUE THREAD

**Issue by skonves** [skonves/express-http-context#3]
Add support to the Async Hooks API in Node 8 rather than CLS

**Comment by skonves** [comment]
https://github.com/AndreasMadsen/node/blob/4ba706f01f4692abcec67d0ad915e4b1f6ccdde5/doc/api/async_hooks.md

**Comment by amiram** [comment]
I've created a fork of this repo with cls-hooked. Now you can use it with async/await. https://www.npmjs.com/package/express-cls-hooked

**Comment by skonves** [comment]
@amiram First of all, thank you very much for your help on this project!

Without objection, I am going to merge your contributions back into this repository and release it as a new major version.

**Comment by amiram** [comment]
You can merge it, although I think a fork is better, so that anyone who wants to use your lib with node <8 won't need to specify a version when installing. Existing users also would not have to worry about upgrading to the new version by mistake.
