### ISSUE TITLE
Incompatible with node 10.15.1

### ISSUE THREAD

**Issue by dmitriyp-comigo** [skonves/express-http-context#34]
I'm using node 10.15.1. It looks like must be worked since 10.15.1 is >=10.4.0. But It does not work:

npm install --save express-http-context

npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for express-http-context@1.2.0: wanted: {"node":">=8.0.0 - <10.0.0 || >=10.4.0"} (current: {"node":"10.15.1","npm":"6.4.1"})
npm ERR! notsup Not compatible with your version of node/npm: express-http-context@1.2.0
npm ERR! notsup Not compatible with your version of node/npm: express-http-context@1.2.0
npm ERR! notsup Required: {"node":">=8.0.0 - <10.0.0 || >=10.4.0"}
npm ERR! notsup Actual:   {"npm":"6.4.1","node":"10.15.1"}

**Comment by dmitriyp-comigo** [comment]
Please check my PR https://github.com/skonves/express-http-context/pull/35

**Comment by SimenB** [comment]
close this?
