### ISSUE TITLE
body-parser and async are breaking CLS

### ISSUE THREAD

**Issue by amiram** [skonves/express-http-context#4]
To avoid weird behavior with express:
1. Make sure you require `express-http-context` in the first row of your app. Some popular pkgs use async which breaks CLS.
2. If you use body-parser, register it in express before you register `express-http-context`'s middleware. I did after seeing that all post requests lost the context.

**Comment by skonves** [comment]
Thanks for the feedback and thanks for the usage notes!  Which versions of node have you been using `express-http-context` with?

**Comment by amiram** [comment]
node v6.10.2

**Comment by amiram** [comment]
@skonves I think you should add this to the readme. It could save many hours.

**Comment by wolever** [comment]
🎉 I just spent an hour on this one too. Thanks for documenting it!

Any idea why it's happening? Debugging through `body-parser` I don't see any reason it _should_ happen, since this is the (very normal looking) callback that doesn't get hooked with CLS:

```
  // read body
  debug('read body')
  getBody(stream, opts, function (error, body) {
    // … this callback …
  })
```

**Comment by skonves** [comment]
Thanks for the feedback!

What version of node are you running and what OS are you running on?  FWIW, there is a known issue with how node 10 handles async/await (see issue #8).

**Comment by shaunc869** [comment]
It looks like the bug linked in the readme has been marked closed, can httpContext be updated to work with node 10 now?

**Comment by skonves** [comment]
Absolutely 👍

Node 10.4.0 and later include the fixed version of V8.

**Comment by 2Marks** [comment]
context request lost when doing multiple API calls, but works if it is just one API call

**Comment by vg2ls** [comment]
any update about that? seems to strange. I am using directly cls-hooked.

**Comment by jatinb92** [comment]
Any update on this ... Any one?

**Comment by devonik** [comment]
This is the way 💯 . I just updated body-parser to latest 1.20.2 and the context is there. Event if the app.use(httpContext.middleware); is defined above app.use(bodyParser)
