### ISSUE TITLE
Is there a way to access a CLS namespace from another file?

### ISSUE THREAD

**Issue by CSP197** [skonves/express-http-context#40]
I was reading over [node-request-context's README](https://github.com/guyguyon/node-request-context#node-request-context) and I saw the getNamespace function which allows accessing a namespace set in one file to be accessed from another file.

Is there such a functionality in this package?

**Comment by rohitsud** [comment]
Yes, this namespace can be accessed from any other file (a module running in the same NodeJS process).

**Comment by CSP197** [comment]
Gotcha 👍 

I wanted to ask if there a more elegant way than declaring the cls namespace variable

`var ns = require('express-http-context').ns;`
